[package]
name = "sattools"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "1.5.0"
clap = { version = "4.5.0", features = ["derive"] }
env_logger = "0.11.2"
fxhash = "0.2.1"
indicatif = "0.17.8"
itertools = "0.12.1"
log = "0.4.20"
rayon = "1.8.1"

[dev-dependencies]
env_logger = "0.11.2"
